source ~/.vim/defaults.vim
source ~/.vim/plugins.vim
source ~/.vim/nerdtree.vim
source ~/.vim/nerdcommenter.vim
source ~/.vim/coc.vim
source ~/.vim/ale.vim
source ~/.vim/helpers.vim
source ~/.vim/colors.vim
source ~/.vim/mappings.vim
